### PR TITLE
Fix linkis cli async exeute throw npe

### LINKED ISSUE #4869: [Bug] [Linkis-Cli] linkis cli async exeute throw npe
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-computation-governance

### Steps to reproduce

1. linkis-cli --async true 
2. get error 
```
Failed to execute jobjava.lang.NullPointerException
        at org.apache.linkis.cli.application.interactor.job.interactive.InteractiveJob.run(InteractiveJob.java:120)
        at org.apache.linkis.cli.application.LinkisClientApplication.main(LinkisClientApplication.java:110)


############Execute Error!!!########
```

### Expected behavior

no error

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by peacewong**
### What is the purpose of the change
Fix linkis cli async execute throw npe. close #4869

### Related issues/PRs

Related issues: #4869

### CODE REVIEW

File: linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/EMRestfulApi.java
Comment (rarexixi) [inline linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/EMRestfulApi.java:1]: Consider using `getOrDefault` instead

File: linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/EMRestfulApi.java [hunk 1]
```diff
@@ -359,9 +359,14 @@ public Message executeECMOperation(HttpServletRequest req, @RequestBody JsonNode
           "Fail to process the operation parameters, cased by "
               + ExceptionUtils.getRootCauseMessage(e));
     }
-    String engineConnInstance = (String) parameters.get("engineConnInstance");
-    return executeECMOperation(
-        ecmNode, engineConnInstance, new ECMOperateRequest(userName, parameters));
+    if (parameters.containsKey("engineConnInstance")) {
```
Comment (rarexixi) [inline linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/EMRestfulApi.java:362]: Consider using `getOrDefault` instead

**Comment by rarexixi** [comment]
LGTM.

**Review by rarexixi — APPROVED** [review]
It's OK
