### PR TITLE
[Bug][ECM]Script to kill process should to skip ECM pid

### LINKED ISSUE #4732: [Bug][ECM]Script to kill process should to skip ECM pid
### Search before asking

- [X] I searched the [issues](https://github.com/apache/linkis/issues) and found no similar issues.

### Linkis Component

linkis-computation-governance

### Steps to reproduce

Script to kill process should to skip ECM pid,Prevent wrong kill ECM process

### Expected behavior

skip ecm process

### Your environment

- Linkis version used: 1.1.2
- Environment name and version:
    - cdh-5.14.2
    - hdp-3.1.5
    - hive-2.1.1
    - spark-3.2.1
    - scala-2.12.2
    - jdk 1.8.0_121
    - ....

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by peacewong**
### What is the purpose of the change

Should to skip ECM pid，close  #4732

### CODE REVIEW

File: linkis-dist/package/sbin/kill-process-by-pid.sh [hunk 1]
```diff
@@ -14,68 +14,59 @@
...
-  local children=$(pgrep -P ${ppid})
+cd `dirname $0`
+cd ..
+INSTALL_HOME=`pwd`
+# set LINKIS_HOME
+if [ "$LINKIS_HOME" = "" ]; then
+  export LINKIS_HOME=$INSTALL_HOME
+fi
+if [ "$LINKIS_LOG_DIR" = "" ]; then
+  export LINKIS_LOG_DIR="/data/bdp/logs/linkis"
```
Comment (guoshupei) [inline linkis-dist/package/sbin/kill-process-by-pid.sh:25]: Is it better to change it to `LINKIS_LOG_DIR="$LINKIS_HOME/logs" `

Comment (peacewong) [reply linkis-dist/package/sbin/kill-process-by-pid.sh:25]: ok,Thanks

**Review by casionone — APPROVED** [review]
